/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "index.html",
    "./src/**/*.{vue,ts}"
  ],
  theme: {
    extend: {
      fontFamily: {
        'sans': ['Inter', 'Roboto', 'sans-serif'],
      },
      screens: {
        '3xl': '1920px',
      },
      colors: {
        'csps-primary': '#4A2558',
        'csps-secondary': '#D4A923',
        'csps-tertiary': '#06203F',

        "primary": "var(--md-sys-color-primary)",
        "on-primary": "var(--md-sys-color-on-primary)",
        "primary-container": "var(--md-sys-color-primary-container)",
        "on-primary-container": "var(--md-sys-color-on-primary-container)",
        "primary-fixed": "var(--md-sys-color-primary-fixed)",
        "on-primary-fixed": "var(--md-sys-color-on-primary-fixed)",
        "primary-fixed-dim": "var(--md-sys-color-primary-fixed-dim)",
        "on-primary-fixed-variant": "var(--md-sys-color-on-primary-fixed-variant)",
        "secondary": "var(--md-sys-color-secondary)",
        "on-secondary": "var(--md-sys-color-on-secondary)",
        "secondary-container": "var(--md-sys-color-secondary-container)",
        "on-secondary-container": "var(--md-sys-color-on-secondary-container)",
        "secondary-fixed": "var(--md-sys-color-secondary-fixed)",
        "on-secondary-fixed": "var(--md-sys-color-on-secondary-fixed)",
        "secondary-fixed-dim": "var(--md-sys-color-secondary-fixed-dim)",
        "on-secondary-fixed-variant": "var(--md-sys-color-on-secondary-fixed-variant)",
        "tertiary": "var(--md-sys-color-tertiary)",
        "on-tertiary": "var(--md-sys-color-on-tertiary)",
        "tertiary-container": "var(--md-sys-color-tertiary-container)",
        "on-tertiary-container": "var(--md-sys-color-on-tertiary-container)",
        "tertiary-fixed": "var(--md-sys-color-tertiary-fixed)",
        "on-tertiary-fixed": "var(--md-sys-color-on-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--md-sys-color-tertiary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--md-sys-color-on-tertiary-fixed-variant)",
        "error": "var(--md-sys-color-error)",
        "error-container": "var(--md-sys-color-error-container)",
        "on-error": "var(--md-sys-color-on-error)",
        "on-error-container": "var(--md-sys-color-on-error-container)",
        "background": "var(--md-sys-color-background)",
        "on-background": "var(--md-sys-color-on-background)",
        "outline": "var(--md-sys-color-outline)",
        "inverse-on-surface": "var(--md-sys-color-inverse-on-surface)",
        "inverse-surface": "var(--md-sys-color-inverse-surface)",
        "inverse-primary": "var(--md-sys-color-inverse-primary)",
        "shadow": "var(--md-sys-color-shadow)",
        "surface-tint": "var(--md-sys-color-surface-tint)",
        "outline-variant": "var(--md-sys-color-outline-variant)",
        "scrim": "var(--md-sys-color-scrim)",
        "surface": "var(--md-sys-color-surface)",
        "on-surface": "var(--md-sys-color-on-surface)",
        "surface-variant": "var(--md-sys-color-surface-variant)",
        "on-surface-variant": "var(--md-sys-color-on-surface-variant)",
        "surface-container-highest": "var(--md-sys-color-surface-container-highest)",
        "surface-container-high": "var(--md-sys-color-surface-container-high)",
        "surface-container": "var(--md-sys-color-surface-container)",
        "surface-container-low": "var(--md-sys-color-surface-container-low)",
        "surface-container-lowest": "var(--md-sys-color-surface-container-lowest)",
        "surface-dim": "var(--md-sys-color-surface-dim)",
        "surface-bright": "var(--md-sys-color-surface-bright)",

        /* primary */
        "primary0": "#000000",
        "primary4": "#250200",
        "primary5": "#2a0300",
        "primary6": "#2e0300",
        "primary10": "#3d0600",
        "primary12": "#450700",
        "primary17": "#570c00",
        "primary20": "#630f00",
        "primary22": "#6b1100",
        "primary24": "#731300",
        "primary25": "#771400",
        "primary30": "#8a1b03",
        "primary35": "#9b280e",
        "primary40": "#ac3419",
        "primary50": "#ce4c2f",
        "primary60": "#f06445",
        "primary70": "#ff8a70",
        "primary80": "#ffb4a3",
        "primary87": "#ffcfc5",
        "primary90": "#ffdad2",
        "primary92": "#ffe2dc",
        "primary94": "#ffe9e5",
        "primary95": "#ffede9",
        "primary96": "#fff0ed",
        "primary98": "#fff8f6",
        "primary99": "#fffbff",
        "primary100": "#ffffff",

        /* secondary */
        "secondary0": "#000000",
        "secondary4": "#1c0805",
        "secondary5": "#200b07",
        "secondary6": "#230d08",
        "secondary10": "#2c1510",
        "secondary12": "#311914",
        "secondary17": "#3d231e",
        "secondary20": "#442a24",
        "secondary22": "#492e28",
        "secondary24": "#4e322c",
        "secondary25": "#51342e",
        "secondary30": "#5d3f39",
        "secondary35": "#6a4b44",
        "secondary40": "#77574f",
        "secondary50": "#926f67",
        "secondary60": "#ae8880",
        "secondary70": "#caa299",
        "secondary80": "#e7bdb4",
        "secondary87": "#fcd0c7",
        "secondary90": "#ffdad2",
        "secondary92": "#ffe2dc",
        "secondary94": "#ffe9e5",
        "secondary95": "#ffede9",
        "secondary96": "#fff0ed",
        "secondary98": "#fff8f6",
        "secondary99": "#fffbff",
        "secondary100": "#ffffff",

        /* tertiary */
        "tertiary0": "#000000",
        "tertiary4": "#140d00",
        "tertiary5": "#171000",
        "tertiary6": "#1a1200",
        "tertiary10": "#241a00",
        "tertiary12": "#291e00",
        "tertiary17": "#352800",
        "tertiary20": "#3c2f04",
        "tertiary22": "#413308",
        "tertiary24": "#46380c",
        "tertiary25": "#483a0e",
        "tertiary30": "#544519",
        "tertiary35": "#615124",
        "tertiary40": "#6d5d2e",
        "tertiary50": "#887544",
        "tertiary60": "#a38f5b",
        "tertiary70": "#bea973",
        "tertiary80": "#dbc58c",
        "tertiary87": "#efd89e",
        "tertiary90": "#f8e0a6",
        "tertiary92": "#fee6ab",
        "tertiary94": "#ffecc1",
        "tertiary95": "#ffefcd",
        "tertiary96": "#fff2d9",
        "tertiary98": "#fff8f1",
        "tertiary99": "#fffbff",
        "tertiary100": "#ffffff",

        /* neutral */
        "neutral0": "#000000",
        "neutral4": "#120d0c",
        "neutral5": "#15100e",
        "neutral6": "#181211",
        "neutral10": "#201a19",
        "neutral12": "#251e1d",
        "neutral17": "#2f2827",
        "neutral20": "#362f2d",
        "neutral22": "#3b3331",
        "neutral24": "#3f3736",
        "neutral25": "#413a38",
        "neutral30": "#4d4543",
        "neutral35": "#59504f",
        "neutral40": "#655c5a",
        "neutral50": "#7f7573",
        "neutral60": "#998e8c",
        "neutral70": "#b4a9a6",
        "neutral80": "#d0c4c1",
        "neutral87": "#e4d7d5",
        "neutral90": "#ede0dd",
        "neutral92": "#f3e5e3",
        "neutral94": "#f8ebe8",
        "neutral95": "#fbeeeb",
        "neutral96": "#fef1ee",
        "neutral98": "#fff8f6",
        "neutral99": "#fffbff",
        "neutral100": "#ffffff",
      }
    }
  }
}