<template>
  <div class="container mx-auto px-16 md:px-20 lg:px-32 xl:px-60">
    <div class="flex flex-col my-5">
      <div class="mb-12">
        <h1 class="text-center !text-3xl text-slate-200 mb-2 font-extrabold">Privacy Policy</h1>
        <PolicyDescription class="mb-0 text-sm !text-center">Updated at March 5, 2022</PolicyDescription>
      </div>
      
      <PolicyDescription>
        Mavyfaby (“we,” “our,” or “us”) is committed to protecting your privacy. 
        This Privacy Policy explains how your personal information is collected, used, and disclosed by Mavyfaby.
      </PolicyDescription>

      <PolicyDescription>
        This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application, Mavyfaby.
        By accessing or using our Service, you signify that you have read, understood, and agree to our collection,
        storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
      </PolicyDescription>

      <PolicyHeader id="definitions-and-key-terms">Definitions and key terms</PolicyHeader>

      <PolicyDescription>
        To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:
      </PolicyDescription>

      <ul>
        <li>Cookie:&nbsp;small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
        <li>Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Mavyfaby, that is responsible for your information under this Privacy Policy.</li>
        <li>Country: where Mavyfaby or the owners/founders of Mavyfaby are based, in this case is Philippines</li>
        <li>Customer:&nbsp;refers to the company, organization or person that signs up to use the Mavyfaby Service to manage the relationships with your consumers or service users.</li>
        <li>Device:&nbsp;any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Mavyfaby and use the services.</li>
        <li>IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
        <li>Personnel:&nbsp;refers to those individuals who are employed by Mavyfaby or are under contract to perform a service on behalf of one of the parties.</li>
        <li>Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
        <li>Service: refers to the service provided by Mavyfaby as described in the relative terms (if available) and on this platform.</li>
        <li>Third-party service:&nbsp;refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
        <li>Website: Mavyfaby's site, which can be accessed via this URL: https://mavyfaby.me</li>
        <li>You: a person or entity that is registered with Mavyfaby to use the Services.</li>
      </ul>
      <br />

      <PolicyHeader id="what-information-do-we-collect">What Information Do We Collect?</PolicyHeader>
      <PolicyDescription>We collect information from you when you contact us via the form in our website, such as:</PolicyDescription>
      
      <ul>
        <li>Name / Username</li>
        <li>Email Addresses</li>
      </ul>
      <br />

      <PolicyHeader id="when-does-mavyfaby-use-end-user-information-from-third-parties">
        When does Mavyfaby use end user information from third parties?
      </PolicyHeader>
      <PolicyDescription>Mavyfaby will only collect End User Data required to contact us via the contact page form. There were no third-parties involved.</PolicyDescription>

      <PolicyHeader id="do-we-share-the-information-we-collect-with-third-parties">
        Do we share the information we collect with third parties?
      </PolicyHeader>
      <PolicyDescription>There were no third-parties involved. Therefore, sharing of information is impossible.</PolicyDescription>

      <PolicyHeader id="where-and-when-is-information-collected-from-customers-and-end-users">
        Where and when is information collected from customers and end users?
      </PolicyHeader>
      <PolicyDescription>Mavyfaby will collect personal information that you submit to us via the contact form in our website, as described above.</PolicyDescription>

      <PolicyHeader id="how-do-we-use-the-information-we-collect">How Do We Use The Information We Collect?</PolicyHeader>
      <PolicyDescription>Any of the information we collect from you may be used in one of the following ways:</PolicyDescription>

      <ul>
        <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
        <li>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)</li>
        <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
        <li>To administer a contest, promotion, survey or other site feature</li>
        <li>To answer your questions</li>
      </ul>
      <br />

      <PolicyHeader id="how-do-we-use-your-email-address">How Do We Use Your Email Address?</PolicyHeader>
      <PolicyDescription>
        By submitting your email address on this website, you agree to receive emails from us.
        We only send emails to people who have authorized us to contact them, either directly, or through a third party.
        We do not send unsolicited commercial emails, because we hate spam as much as you do.
        Email addresses submitted only through the contact form page will be used for the sole purpose of
        sending you information and updates pertaining to your message for us.
        If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy.
        <span class="italic">We only email to you if you have questions from us.</span>
      </PolicyDescription>

      <PolicyHeader id="how-long-do-we-keep-your-information">How Long Do We Keep Your Information?</PolicyHeader>
      <PolicyDescription>
        We keep your information only so long as we need it to provide Mavyfaby to you and fulfill the purposes described in this policy.
        This is also the case for anyone that we <span class="italic">do not</span> share your information with and who carries out services on our behalf.
        When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations,
        we'll either remove it from our systems or depersonalize it so that we can't identify you.
      </PolicyDescription>

      <PolicyHeader id="how-do-we-protecty-your-information">How Do We Protect Your Information?</PolicyHeader>
      <PolicyDescription>
        We implement a variety of security measures to maintain the safety of your personal information when you send us a message in our contact page.
        We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted
        into our servers database only to be accessible by those authorized with special access rights to such systems, and are required to keep
        the information confidential. After a submiting a form, your private information (name and email address) is never kept on file.
        We cannot, however, ensure or warrant the absolute security of any information you transmit to Mavyfaby or guarantee that your information
        on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.
      </PolicyDescription>

      <PolicyHeader id="could-my-information-be-transferred-to-other-countries">Could my information be transferred to other countries?</PolicyHeader>
      <PolicyDescription>
        Mavyfaby is incorporated in Philippines. Information collected via our website, through direct interactions with you,
        or from use of our help services will <span class="italic">not</span> be transferred to any country.
      </PolicyDescription>

      <PolicyHeader id="is-the-information-collected-through-the-mavyfaby-service-secure">
        Is the information collected through the Mavyfaby Service secure?
      </PolicyHeader>
      <PolicyDescription>
        We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard,
        prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof,
        including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies.
        Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security.
        If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct
        will be the standards used to measure our compliance with that duty.
      </PolicyDescription>

      <PolicyHeader id="can-i-update-or-correct-my-information">Can I update or correct my information?</PolicyHeader>
      <PolicyDescription>
        The rights you have to request updates or corrections to the information Mavyfaby collects depend on your relationship with Mavyfaby.
      </PolicyDescription>
      <PolicyDescription>
        Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows.
        You can&nbsp;contact us in order to update or correct your personally identifiable information.
      </PolicyDescription>
      <PolicyDescription>
        You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us
        from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may
        exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information
        stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted as appropriate,
        as soon as and to the extent reasonably and technically practicable. If you are an end user and wish to update, delete, or receive any
        information we have about you, you may do so by contacting us via email, phone, or by filling up the contact form.
      </PolicyDescription>
      
      <PolicyHeader id="governing-law">Governing Law</PolicyHeader>
      <PolicyDescription>
        This Privacy Policy is governed by the laws of Philippines without regard to its conflict of laws provision. You consent to the exclusive
        jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy
        except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.
      </PolicyDescription>
      <PolicyDescription>
        The laws of Philippines, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website
        may also be subject to other local, state, national, or international laws.
      </PolicyDescription>
      <PolicyDescription>
        By using Mavyfaby or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy,
        you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting
        of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.
      </PolicyDescription>

      <PolicyHeader id="your-consent">Your Consent</PolicyHeader>
      <PolicyDescription>
        We've updated our&nbsp;Privacy Policy&nbsp;to provide you with complete transparency into what is being set when you visit our site and how it's being used.
        By using our Mavyfaby, you hereby consent to our Privacy Policy and agree to its terms.
      </PolicyDescription>

      <PolicyHeader id="linkes-to-other-websites">Links to Other Websites</PolicyHeader>
      <PolicyDescription>
        This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by Mavyfaby.
        We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or
        checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy
        is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that
        website's own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
      </PolicyDescription>
      
      <PolicyHeader id="cookies">Cookies</PolicyHeader>
      <PolicyDescription>
        Mavyfaby uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or
        mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use.
        However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every
        time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of
        Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally
        Identifiable Information in Cookies.
      </PolicyDescription>
      
      
      <PolicyHeader id="blocking-and-disabling-cookies-and-similar-technologies">Blocking and disabling cookies and similar technologies</PolicyHeader>
      <PolicyDescription>
        Wherever you're located you may also set your browser to block cookies and similar technologies,
        but this action may block our essential cookies and prevent our website from functioning properly,
        and you may not be able to fully utilize all of its features and services.
        You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences)
        if you block cookies on your browser. Different browsers make different controls available to you.
        Disabling a cookie or category of cookie does not delete the cookie from your browser,
        you will need to do this yourself from within your browser,
        you should visit your browser's help menu for more information.
      </PolicyDescription>

      <PolicyHeader id="kids-privacy">Kids' Privacy</PolicyHeader>
      <PolicyDescription>
        We collect information only in our contact form, we don't know the age of whoever contacting from us since we only collect name and email address.
        If someone contacting Us under the age of 13 and if You are a parent or guardian and You are aware that Your child has provided Us with Personal
        Data without your permission, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without
        verification of parental consent, We take steps to remove that information from Our servers.
      </PolicyDescription>

      <PolicyHeader id="changes-to-our-privacy-policy">Changes To Our Privacy Policy</PolicyHeader>
      <PolicyDescription>
        We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies.
        Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an
        opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy.
        If you do not want to agree to this or any updated Privacy Policy, you can delete your account.
      </PolicyDescription>
      
      <PolicyHeader id="tracking-technologies">Tracking Technologies</PolicyHeader>
      <ul>
        <li>
          <div class="mb-5">Cookies</div>
          <PolicyDescription>
            We use Cookies to enhance the performance and functionality of our website but are non-essential to their use.
            However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter
            your login details every time you visit the website as we would not be able to remember that you had logged in previously.
          </PolicyDescription>
        </li>
        
        <li>
          <div class="mb-5">Local Storage</div>
          <PolicyDescription>
            Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side data.
            Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information
            stored in the HTTP request header.
          </PolicyDescription>
        </li>
      </ul>

      <PolicyHeader id="information-about-general-data-protection-regulation">
        Information about General Data Protection Regulation (GDPR)
      </PolicyHeader>
      <PolicyDescription>
        We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of our Privacy Policy we are going
        to explain exactly how and why is this data collected, and how we maintain this data under protection from being replicated or used in the wrong way.
      </PolicyDescription>

      <PolicyHeader id="what-is-gdpr">What is GDPR?</PolicyHeader>
      <PolicyDescription>
        GDPR is an EU-wide privacy and data protection law that regulates how EU residents' data is
        protected by companies and enhances the control&nbsp;the EU residents have, over their personal data.
      </PolicyDescription>
      <PolicyDescription>
        The GDPR is relevant to any globally operating company and not just the EU-based businesses and EU residents. Our customers' data is important
        irrespective of where they are located, which is why we have implemented GDPR controls as our baseline standard for all our operations worldwide.
      </PolicyDescription>

      <PolicyHeader id="what-is-personal-data">What is personal data?</PolicyHeader>
      <PolicyDescription>
        Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used on its own, or in
        combination with other pieces of information, to identify a person. Personal data extends beyond a person's name or email address. Some examples include
        financial information, political opinions, genetic data, biometric data, IP addresses, physical address, sexual orientation, and ethnicity.
      </PolicyDescription>
      <PolicyDescription>The Data Protection Principles include requirements such as:</PolicyDescription>

      <ul>
        <li>Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.</li>
        <li>Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.</li>
        <li>Personal data should be held no longer than necessary to fulfil its purpose.</li>
        <li>People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.</li>
      </ul><br />
      
      <PolicyHeader id="why-is-gdpr-important">Why is GDPR important?</PolicyHeader>
      <PolicyDescription>
        GDPR adds some new requirements regarding how companies should protect individuals' personal data that they collect and process.
        It also raises the stakes for compliance by increasing enforcement and imposing greater fines for breach. Beyond these facts it's simply the
        right thing to do. At Mavyfaby we strongly believe that your data privacy is very important and we already have solid security and privacy practices
        in place that go beyond the requirements of this new regulation.
      </PolicyDescription>

      <PolicyHeader id="individual-data-subjects-rights-data-access-portability-and-deletion">
        Individual Data Subject's Rights - Data Access, Portability and Deletion
      </PolicyHeader>
      <PolicyDescription>
        We are committed to helping our customers meet the&nbsp;data subject rights requirements of GDPR. Mavyfaby processes or stores all personal data
        in fully vetted, DPA compliant vendors. We do store all conversation and personal data for up to 5 years. In which case, we dispose of all data
        in accordance with our Privacy Policy.
      </PolicyDescription>
      <PolicyDescription>
        We are aware that if you are working with EU customers, you need to be able to provide them with the ability to access, update, retrieve and remove
        personal data. We got you! We've been set up as self service from the start and have always given you access to your data and your customers data.
        Our customer&nbsp;support team is here for you to answer any questions you might have about working with the API.
      </PolicyDescription>

      <PolicyHeader id="california-residents">California Residents</PolicyHeader>
      <PolicyDescription>
        The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it, the categories
        of sources from whom we collect Personal Information, which we have explained above.
      </PolicyDescription>
      <PolicyDescription>
        We are also required to communicate information about rights California residents have under California law. You may exercise the following rights:
      </PolicyDescription>

      <ul>
        <li>Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</li>
        <li>Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</li>
        <li>Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</li>
        <li>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</li>
      </ul><br />

      <PolicyDescription>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</PolicyDescription>
      <PolicyDescription>We do not sell the Personal Information of our users.</PolicyDescription>
      <PolicyDescription>For more information about these rights, please contact us.</PolicyDescription>

      <PolicyHeader id="california-online-privacy-protection-art">California Online Privacy Protection Act (CalOPPA)</PolicyHeader>
      <PolicyDescription>
        CalOPPA requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect
        Personal Information, which we have explained above.
      </PolicyDescription>
      <PolicyDescription>CalOPPA users have the following rights:</PolicyDescription>

      <ul>
        <li>Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</li>
        <li>Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</li>
        <li>Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</li>
        <li>Right to request that a business that sells a consumer's personal data, not sell the consumer's personal data.</li>
      </ul>

      <PolicyDescription>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</PolicyDescription>
      <PolicyDescription>We do not sell the Personal Information of our users.</PolicyDescription>
      <PolicyDescription>For more information about these rights, please contact us.</PolicyDescription>

      <PolicyHeader id="contact-us">Contact Us</PolicyHeader>
      <PolicyDescription>Don't hesitate to contact us if you have any questions.</PolicyDescription>

      <ul>
        <li>Via Email: me@mavyfaby.me</li>
        <li>Via Phone Number: 09229629963</li>
        <li>Via this Link: https://mavyfaby.me/#contact</li>
      </ul>
    </div>
  </div>
</template>

<script setup>
import PolicyHeader from "./components/PolicyHeader.vue";
import PolicyDescription from "./components/PolicyDescription.vue";
</script>

<style scoped>
ul {
  @apply text-slate-400 text-justify;
}

ul {
  @apply list-disc ml-12;
}

ul li {
  @apply my-2;
}


</style>